import type { Series, WatchProgress } from '@/types';

// ============================================================
// CineVerse — Premium TV Series Mock Data
// ============================================================

export const series: Series[] = [
  {
    id: 's1',
    title: 'The Last Kingdom',
    poster: 'https://picsum.photos/seed/lastkingdom/400/600',
    backdrop: 'https://picsum.photos/seed/lastkingdombg/1200/680',
    description: 'Set in the late 9th century AD, when Alfred the Great rules over the last kingdom of Wessex. A young Saxon nobleman is captured and raised by Vikings, torn between his loyalties to both sides as the battle for England rages on. This epic saga of war, love, and betrayal follows one man\'s quest to reclaim his birthright and unite a fractured nation against invading forces.',
    genre: ['Drama', 'Action', 'History'],
    year: 2022,
    rating: 9.1,
    ratingCount: 245000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2022',
        episodes: [
          { id: 's1e1', number: 1, title: 'The Awakening', description: 'Young Uhtred witnesses the brutal Saxon defeat and is taken by Danish warlord Earl Ragnar.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/s1e1/320/180', rating: 9.3, airDate: '2022-03-04' },
          { id: 's1e2', number: 2, title: 'Shadow of the Dane', description: 'Uhtred grows up among the Danes and learns their ways, forming bonds that will shape his destiny.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/s1e2/320/180', rating: 9.1, airDate: '2022-03-11' },
          { id: 's1e3', number: 3, title: 'Blood and Oath', description: 'A devastating betrayal forces Uhtred to flee, beginning his long journey back to Bebbanburg.', duration: '61 min', thumbnail: 'https://picsum.photos/seed/s1e3/320/180', rating: 9.4, airDate: '2022-03-18' },
          { id: 's1e4', number: 4, title: 'The Shield Wall', description: 'The great battle begins as Saxon and Danish forces collide on the open fields of Wessex.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/s1e4/320/180', rating: 9.5, airDate: '2022-03-25' },
          { id: 's1e5', number: 5, title: 'King\'s Mercy', description: 'Alfred must decide Uhtred\'s fate as political tensions threaten to tear the kingdom apart.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/s1e5/320/180', rating: 8.9, airDate: '2022-04-01' },
          { id: 's1e6', number: 6, title: 'Two Kings', description: 'The final confrontation as Uhtred must choose between two worlds and two kings.', duration: '68 min', thumbnail: 'https://picsum.photos/seed/s1e6/320/180', rating: 9.6, airDate: '2022-04-08' },
        ],
      },
      {
        number: 2,
        year: '2023',
        episodes: [
          { id: 's2e1', number: 1, title: 'The Exile', description: 'Uhtred is banished from Wessex and must forge new alliances in the frozen North.', duration: '59 min', thumbnail: 'https://picsum.photos/seed/s2e1/320/180', rating: 9.2, airDate: '2023-01-15' },
          { id: 's2e2', number: 2, title: 'Winter\'s Edge', description: 'A harsh winter tests the strength of all factions as supplies run thin.', duration: '57 min', thumbnail: 'https://picsum.photos/seed/s2e2/320/180', rating: 9.0, airDate: '2023-01-22' },
          { id: 's2e3', number: 3, title: 'The False King', description: 'A pretender to the throne emerges, threatening to plunge England into civil war.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/s2e3/320/180', rating: 9.3, airDate: '2023-01-29' },
          { id: 's2e4', number: 4, title: 'Fire and Sword', description: 'The siege of a great fortress brings old enemies face to face once more.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/s2e4/320/180', rating: 9.4, airDate: '2023-02-05' },
          { id: 's2e5', number: 5, title: 'Dawn of Reckoning', description: 'Uhtred rallies his forces for the final push to reclaim his homeland.', duration: '70 min', thumbnail: 'https://picsum.photos/seed/s2e5/320/180', rating: 9.5, airDate: '2023-02-12' },
        ],
      },
    ],
    cast: [
      { name: 'Alexander Drake', role: 'Uhtred of Bebbanburg', photo: 'https://picsum.photos/seed/cast1/100/100' },
      { name: 'Elena Vasquez', role: 'Lady Aethelflaed', photo: 'https://picsum.photos/seed/cast2/100/100' },
      { name: 'Marcus Chen', role: 'Earl Ragnar', photo: 'https://picsum.photos/seed/cast3/100/100' },
      { name: 'Sophie Laurent', role: 'Queen Iseult', photo: 'https://picsum.photos/seed/cast4/100/100' },
      { name: 'James O\'Brien', role: 'Father Beocca', photo: 'https://picsum.photos/seed/cast5/100/100' },
    ],
    status: 'Completed',
    studio: 'Crown Television',
    country: 'United Kingdom',
    language: 'English',
    totalEpisodes: 11,
    featured: true,
    trending: true,
  },
  {
    id: 's2',
    title: 'Neon Shadows',
    poster: 'https://picsum.photos/seed/neonshadows/400/600',
    backdrop: 'https://picsum.photos/seed/neonshadowsbg/1200/680',
    description: 'In a rain-soaked megacity of 2089, a disgraced detective with cybernetic implants uncovers a conspiracy that links the city\'s most powerful corporations to a series of impossible murders. As she digs deeper, she discovers the truth about her own past and a technology that could either save humanity or destroy it forever.',
    genre: ['Sci-Fi', 'Thriller', 'Drama'],
    year: 2024,
    rating: 9.4,
    ratingCount: 312000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's2e1', number: 1, title: 'Ghost Protocol', description: 'Detective Mira Chen is called to a crime scene where the victim has been killed by their own neural implant.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/ns1e1/320/180', rating: 9.2, airDate: '2024-06-07' },
          { id: 's2e2', number: 2, title: 'Digital Ghosts', description: 'Mira discovers a hidden data trail that leads to the highest levels of Apex Corporation.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/ns1e2/320/180', rating: 9.4, airDate: '2024-06-14' },
          { id: 's2e3', number: 3, title: 'The Breach', description: 'A massive cyberattack paralyzes the city as Mira races against time to find the source.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ns1e3/320/180', rating: 9.5, airDate: '2024-06-21' },
          { id: 's2e4', number: 4, title: 'Mirror Image', description: 'Mira encounters someone who looks exactly like her and claims to be from the future.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/ns1e4/320/180', rating: 9.6, airDate: '2024-06-28' },
          { id: 's2e5', number: 5, title: 'System Collapse', description: 'The conspiracy unravels as the city descends into chaos and Mira must make an impossible choice.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/ns1e5/320/180', rating: 9.7, airDate: '2024-07-05' },
        ],
      },
    ],
    cast: [
      { name: 'Yuki Tanaka', role: 'Detective Mira Chen', photo: 'https://picsum.photos/seed/cast6/100/100' },
      { name: 'David Morales', role: 'Agent Kade', photo: 'https://picsum.photos/seed/cast7/100/100' },
      { name: 'Aria Blackwell', role: 'Dr. Elara Voss', photo: 'https://picsum.photos/seed/cast8/100/100' },
      { name: 'Leon Frost', role: 'CEO Julian Cross', photo: 'https://picsum.photos/seed/cast9/100/100' },
    ],
    status: 'Airing',
    studio: 'Vision Studios',
    country: 'United States',
    language: 'English',
    totalEpisodes: 5,
    featured: true,
    trending: true,
  },
  {
    id: 's3',
    title: 'Whispers of Seoul',
    poster: 'https://picsum.photos/seed/seoulwhispers/400/600',
    backdrop: 'https://picsum.photos/seed/seoulwhispersbg/1200/680',
    description: 'Two childhood friends from vastly different backgrounds reunite in modern-day Seoul. As they navigate the complexities of love, family expectations, and career ambitions, their bond is tested by secrets that have been buried for over a decade. A deeply emotional K-drama about the ties that bind us.',
    genre: ['Drama', 'Romance'],
    year: 2024,
    rating: 8.8,
    ratingCount: 198000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's3e1', number: 1, title: 'Reunion', description: 'After twelve years apart, Ji-ah and Min-ho cross paths at a mutual friend\'s wedding.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/sw1e1/320/180', rating: 8.7, airDate: '2024-02-10' },
          { id: 's3e2', number: 2, title: 'Unspoken Words', description: 'Old feelings resurface as Ji-ah and Min-ho spend a weekend at their childhood neighborhood.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/sw1e2/320/180', rating: 8.9, airDate: '2024-02-17' },
          { id: 's3e3', number: 3, title: 'The Promise', description: 'A long-forgotten promise comes to light, threatening to destroy both their lives.', duration: '68 min', thumbnail: 'https://picsum.photos/seed/sw1e3/320/180', rating: 9.0, airDate: '2024-02-24' },
          { id: 's3e4', number: 4, title: 'Family Ties', description: 'Both families object to the rekindled relationship, forcing a painful decision.', duration: '66 min', thumbnail: 'https://picsum.photos/seed/sw1e4/320/180', rating: 8.8, airDate: '2024-03-02' },
        ],
      },
    ],
    cast: [
      { name: 'Park Soo-jin', role: 'Yoon Ji-ah', photo: 'https://picsum.photos/seed/cast10/100/100' },
      { name: 'Kim Tae-woo', role: 'Lee Min-ho', photo: 'https://picsum.photos/seed/cast11/100/100' },
      { name: 'Han Seo-yeon', role: 'Choi Eun-bi', photo: 'https://picsum.photos/seed/cast12/100/100' },
      { name: 'Lee Joon-hyuk', role: 'Kang Do-jin', photo: 'https://picsum.photos/seed/cast13/100/100' },
    ],
    status: 'Completed',
    studio: 'Seoul Drama House',
    country: 'South Korea',
    language: 'Korean',
    totalEpisodes: 4,
    featured: true,
    trending: true,
  },
  {
    id: 's4',
    title: 'Obsidian Crown',
    poster: 'https://picsum.photos/seed/obsidiancrown/400/600',
    backdrop: 'https://picsum.photos/seed/obsidiancrownbg/1200/680',
    description: 'In a realm where magic is drawn from precious stones, a young thief discovers she is the heir to an ancient throne. With dark forces closing in and allies she cannot trust, she must master forbidden magic and unite warring kingdoms before the Obsidian Crown falls into the wrong hands.',
    genre: ['Fantasy', 'Action', 'Drama'],
    year: 2023,
    rating: 9.0,
    ratingCount: 276000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's4e1', number: 1, title: 'The Stone Thief', description: 'A street thief in the city of Valdren steals a gem that changes her life forever.', duration: '57 min', thumbnail: 'https://picsum.photos/seed/oc1e1/320/180', rating: 8.9, airDate: '2023-09-15' },
          { id: 's4e2', number: 2, title: 'Awakening', description: 'The stolen gem awakens dormant magic within Lyra, attracting dangerous attention.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/oc1e2/320/180', rating: 9.1, airDate: '2023-09-22' },
          { id: 's4e3', number: 3, title: 'The Five Kingdoms', description: 'Lyra begins her journey across the five warring kingdoms, seeking answers about her past.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/oc1e3/320/180', rating: 9.2, airDate: '2023-09-29' },
          { id: 's4e4', number: 4, title: 'Forbidden Magic', description: 'Lyra discovers a forbidden spell that could turn the tide of war.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/oc1e4/320/180', rating: 9.3, airDate: '2023-10-06' },
          { id: 's4e5', number: 5, title: 'Crown of Shadows', description: 'The truth about the Obsidian Crown is revealed in a shocking season finale.', duration: '68 min', thumbnail: 'https://picsum.photos/seed/oc1e5/320/180', rating: 9.5, airDate: '2023-10-13' },
        ],
      },
      {
        number: 2,
        year: '2024',
        episodes: [
          { id: 's4e6', number: 1, title: 'The Usurper', description: 'With the throne usurped, Lyra must build an army from nothing.', duration: '59 min', thumbnail: 'https://picsum.photos/seed/oc2e1/320/180', rating: 9.1, airDate: '2024-03-01' },
          { id: 's4e7', number: 2, title: 'Stone and Blood', description: 'An ancient ritual demands a terrible sacrifice that could change everything.', duration: '61 min', thumbnail: 'https://picsum.photos/seed/oc2e2/320/180', rating: 9.3, airDate: '2024-03-08' },
          { id: 's4e8', number: 3, title: 'The Dragon\'s Gate', description: 'Lyra ventures into the forbidden realm of dragons to forge a powerful alliance.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/oc2e3/320/180', rating: 9.4, airDate: '2024-03-15' },
        ],
      },
    ],
    cast: [
      { name: 'Freya Lindqvist', role: 'Lyra Stoneheart', photo: 'https://picsum.photos/seed/cast14/100/100' },
      { name: 'Rami Hassan', role: 'Prince Kaelen', photo: 'https://picsum.photos/seed/cast15/100/100' },
      { name: 'Isabella Romano', role: 'Sorceress Morwenna', photo: 'https://picsum.photos/seed/cast16/100/100' },
      { name: 'Omar Farouk', role: 'General Thorne', photo: 'https://picsum.photos/seed/cast17/100/100' },
      { name: 'Mei Lin', role: 'Ambassador Jade', photo: 'https://picsum.photos/seed/cast18/100/100' },
    ],
    status: 'Airing',
    studio: 'Eclipse Entertainment',
    country: 'International',
    language: 'English',
    totalEpisodes: 8,
    featured: false,
    trending: true,
  },
  {
    id: 's5',
    title: 'Midnight Kitchen',
    poster: 'https://picsum.photos/seed/midnightkitchen/400/600',
    backdrop: 'https://picsum.photos/seed/midnightkitchenbg/1200/680',
    description: 'After losing her Michelin-starred restaurant, a brilliant but temperamental chef takes over a failing late-night diner in Tokyo. With a ragtag crew of misfits, she transforms the humble eatery into the city\'s most sought-after underground dining experience, one midnight service at a time.',
    genre: ['Drama', 'Comedy'],
    year: 2024,
    rating: 8.6,
    ratingCount: 142000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's5e1', number: 1, title: 'Burnt Offerings', description: 'Chef Ana arrives at the dingy diner and meets her eccentric new team.', duration: '48 min', thumbnail: 'https://picsum.photos/seed/mk1e1/320/180', rating: 8.5, airDate: '2024-04-05' },
          { id: 's5e2', number: 2, title: 'The First Service', description: 'Opening night is a disaster until an unexpected VIP guest changes everything.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/mk1e2/320/180', rating: 8.7, airDate: '2024-04-12' },
          { id: 's5e3', number: 3, title: 'Secret Menu', description: 'Word spreads about the mysterious midnight menu, drawing both praise and envy.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/mk1e3/320/180', rating: 8.8, airDate: '2024-04-19' },
          { id: 's5e4', number: 4, title: 'Rivalry', description: 'A rival chef opens across the street, sparking an intense culinary competition.', duration: '49 min', thumbnail: 'https://picsum.photos/seed/mk1e4/320/180', rating: 8.6, airDate: '2024-04-26' },
        ],
      },
    ],
    cast: [
      { name: 'Sakura Miyamoto', role: 'Chef Ana', photo: 'https://picsum.photos/seed/cast19/100/100' },
      { name: 'Kenji Watanabe', role: 'Takeshi', photo: 'https://picsum.photos/seed/cast20/100/100' },
      { name: 'Marie Dubois', role: 'Sophie', photo: 'https://picsum.photos/seed/cast21/100/100' },
    ],
    status: 'Completed',
    studio: 'Tokyo Story Co.',
    country: 'Japan',
    language: 'Japanese',
    totalEpisodes: 4,
    featured: false,
    trending: false,
  },
  {
    id: 's6',
    title: 'The White Lotus',
    poster: 'https://picsum.photos/seed/whitelotus2/400/600',
    backdrop: 'https://picsum.photos/seed/whitelotusbg/1200/680',
    description: 'A sharp social satire following the exploits of various guests and employees at an exclusive tropical resort over the course of a transformative week. As secrets surface and alliances shift, the paradise facade begins to crack, revealing the dark comedy of privilege and human nature.',
    genre: ['Drama', 'Comedy', 'Thriller'],
    year: 2023,
    rating: 8.9,
    ratingCount: 389000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's6e1', number: 1, title: 'Arrivals', description: 'Guests arrive at the exclusive White Lotus resort for what should be a perfect week.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/wl1e1/320/180', rating: 8.8, airDate: '2023-10-20' },
          { id: 's6e2', number: 2, title: 'Crystal Waters', description: 'Underlying tensions surface as the resort\'s pristine image begins to fade.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/wl1e2/320/180', rating: 9.0, airDate: '2023-10-27' },
          { id: 's6e3', number: 3, title: 'Muddy Waters', description: 'A mysterious incident at the spa throws the resort into chaos.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/wl1e3/320/180', rating: 9.2, airDate: '2023-11-03' },
          { id: 's6e4', number: 4, title: 'Departures', description: 'The week ends with revelations that will change everyone forever.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/wl1e4/320/180', rating: 9.4, airDate: '2023-11-10' },
        ],
      },
    ],
    cast: [
      { name: 'Patricia Clarkson', role: 'Victoria', photo: 'https://picsum.photos/seed/cast22/100/100' },
      { name: 'Murray Bartlett', role: 'Armond', photo: 'https://picsum.photos/seed/cast23/100/100' },
      { name: 'Jennifer Coolidge', role: 'Tanya', photo: 'https://picsum.photos/seed/cast24/100/100' },
      { name: 'Connie Britton', role: 'Nicole', photo: 'https://picsum.photos/seed/cast25/100/100' },
    ],
    status: 'Completed',
    studio: 'HBO Original',
    country: 'United States',
    language: 'English',
    totalEpisodes: 4,
    featured: false,
    trending: false,
  },
  {
    id: 's7',
    title: 'Abyss Protocol',
    poster: 'https://picsum.photos/seed/abyssprotocol/400/600',
    backdrop: 'https://picsum.photos/seed/abyssprotocolbg/1200/680',
    description: 'When a deep-sea research station discovers a signal from the ocean floor that predates human civilization, the crew realizes they\'ve awakened something ancient and terrifying. Cut off from the surface and running out of oxygen, they must survive against an intelligence that has waited millions of years to rise.',
    genre: ['Horror', 'Sci-Fi', 'Thriller'],
    year: 2024,
    rating: 8.7,
    ratingCount: 156000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's7e1', number: 1, title: 'Descent', description: 'The research team reaches the deepest part of the ocean and detects an impossible signal.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/ap1e1/320/180', rating: 8.6, airDate: '2024-05-10' },
          { id: 's7e2', number: 2, title: 'The Signal', description: 'Dr. Reyes decodes the signal and discovers coordinates that lead to a massive structure.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/ap1e2/320/180', rating: 8.8, airDate: '2024-05-17' },
          { id: 's7e3', number: 3, title: 'Contact', description: 'First contact with the entity goes catastrophically wrong, trapping the crew.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ap1e3/320/180', rating: 9.0, airDate: '2024-05-24' },
          { id: 's7e4', number: 4, title: 'Pressure', description: 'Oxygen levels drop as the entity begins to infiltrate the station\'s systems.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/ap1e4/320/180', rating: 8.9, airDate: '2024-05-31' },
          { id: 's7e5', number: 5, title: 'The Rise', description: 'In a desperate final act, the crew must prevent the entity from reaching the surface.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/ap1e5/320/180', rating: 9.2, airDate: '2024-06-07' },
        ],
      },
    ],
    cast: [
      { name: 'Ana Reyes', role: 'Dr. Elena Reyes', photo: 'https://picsum.photos/seed/cast26/100/100' },
      { name: 'Tom Hardwick', role: 'Captain Brooks', photo: 'https://picsum.photos/seed/cast27/100/100' },
      { name: 'Nadia Petrova', role: 'Dr. Katya Volkov', photo: 'https://picsum.photos/seed/cast28/100/100' },
    ],
    status: 'Completed',
    studio: 'Deep Blue Pictures',
    country: 'United States',
    language: 'English',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's8',
    title: 'Golden Age',
    poster: 'https://picsum.photos/seed/goldenage/400/600',
    backdrop: 'https://picsum.photos/seed/goldenagebg/1200/680',
    description: 'Set during the 1920s jazz age in Paris, this lavish drama follows three ambitious women from different backgrounds who forge an unlikely alliance to build a fashion empire that challenges the male-dominated industry. Glamour, scandal, and revolution collide in a story of female empowerment.',
    genre: ['Drama', 'History'],
    year: 2024,
    rating: 8.5,
    ratingCount: 134000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's8e1', number: 1, title: 'City of Light', description: 'Three women from different worlds meet at a scandalous Parisian party.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/ga1e1/320/180', rating: 8.4, airDate: '2024-01-12' },
          { id: 's8e2', number: 2, title: 'Silk and Secrets', description: 'The women launch their fashion house while navigating the treacherous Paris elite.', duration: '57 min', thumbnail: 'https://picsum.photos/seed/ga1e2/320/180', rating: 8.6, airDate: '2024-01-19' },
          { id: 's8e3', number: 3, title: 'The Runway', description: 'Their debut fashion show becomes the talk of Paris, attracting dangerous admirers.', duration: '59 min', thumbnail: 'https://picsum.photos/seed/ga1e3/320/180', rating: 8.7, airDate: '2024-01-26' },
        ],
      },
    ],
    cast: [
      { name: 'Camille Rousseau', role: 'Marguerite', photo: 'https://picsum.photos/seed/cast29/100/100' },
      { name: 'Diana Okonkwo', role: 'Adanna', photo: 'https://picsum.photos/seed/cast30/100/100' },
      { name: 'Lena Schmidt', role: 'Hannah', photo: 'https://picsum.photos/seed/cast31/100/100' },
    ],
    status: 'Upcoming',
    studio: 'Lumière Productions',
    country: 'France',
    language: 'French',
    totalEpisodes: 3,
    featured: false,
    trending: false,
  },
  {
    id: 's9',
    title: 'Shadow Detective',
    poster: 'https://picsum.photos/seed/shadowdetective/400/600',
    backdrop: 'https://picsum.photos/seed/shadowdetectivebg/1200/680',
    description: 'A retired police detective who can communicate with the dead is pulled back into service when a serial killer starts leaving messages only the victims can reveal. Each case takes him deeper into a web of corruption that reaches the highest levels of power.',
    genre: ['Mystery', 'Thriller', 'Drama'],
    year: 2023,
    rating: 9.2,
    ratingCount: 287000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's9e1', number: 1, title: 'The Calling', description: 'Former detective Choi receives a vision that leads him to a body in the Han River.', duration: '64 min', thumbnail: 'https://picsum.photos/seed/sd1e1/320/180', rating: 9.1, airDate: '2023-05-05' },
          { id: 's9e2', number: 2, title: 'Echoes', description: 'The ghost of the victim reveals clues that point to a powerful politician.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/sd1e2/320/180', rating: 9.3, airDate: '2023-05-12' },
          { id: 's9e3', number: 3, title: 'The Whisper Network', description: 'Choi discovers other people with similar abilities, forming an unlikely team.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/sd1e3/320/180', rating: 9.2, airDate: '2023-05-19' },
          { id: 's9e4', number: 4, title: 'Red Herring', description: 'A false lead puts Choi in the crosshairs of the very people he\'s investigating.', duration: '66 min', thumbnail: 'https://picsum.photos/seed/sd1e4/320/180', rating: 9.4, airDate: '2023-05-26' },
          { id: 's9e5', number: 5, title: 'Into the Shadows', description: 'The serial killer\'s true identity is revealed in a devastating climax.', duration: '70 min', thumbnail: 'https://picsum.photos/seed/sd1e5/320/180', rating: 9.6, airDate: '2023-06-02' },
        ],
      },
      {
        number: 2,
        year: '2024',
        episodes: [
          { id: 's9e6', number: 1, title: 'Resurrection', description: 'A new case forces Choi to confront a ghost from his own past.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/sd2e1/320/180', rating: 9.3, airDate: '2024-08-02' },
          { id: 's9e7', number: 2, title: 'The Archive', description: 'Choi discovers a secret archive of unsolved cases connected by a single thread.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/sd2e2/320/180', rating: 9.4, airDate: '2024-08-09' },
          { id: 's9e8', number: 3, title: 'Final Judgment', description: 'The ultimate showdown as Choi faces the mastermind behind decades of murders.', duration: '72 min', thumbnail: 'https://picsum.photos/seed/sd2e3/320/180', rating: 9.5, airDate: '2024-08-16' },
        ],
      },
    ],
    cast: [
      { name: 'Song Kang-ho', role: 'Detective Choi', photo: 'https://picsum.photos/seed/cast32/100/100' },
      { name: 'Bae Suzy', role: 'Officer Park', photo: 'https://picsum.photos/seed/cast33/100/100' },
      { name: 'Yoo Ah-in', role: 'Prosecutor Kim', photo: 'https://picsum.photos/seed/cast34/100/100' },
      { name: 'Han So-hee', role: 'Journalist Lee', photo: 'https://picsum.photos/seed/cast35/100/100' },
    ],
    status: 'Completed',
    studio: 'Seoul Noir Studio',
    country: 'South Korea',
    language: 'Korean',
    totalEpisodes: 8,
    featured: false,
    trending: true,
  },
  {
    id: 's10',
    title: 'Orbit',
    poster: 'https://picsum.photos/seed/orbittv/400/600',
    backdrop: 'https://picsum.photos/seed/orbittvbg/1200/680',
    description: 'When Earth\'s first colony ship goes silent halfway to Proxima Centauri, a rescue mission discovers the passengers haven\'t just survived — they\'ve evolved. The rescuers must grapple with the implications of humanity\'s next stage while facing their own transformation.',
    genre: ['Sci-Fi', 'Drama', 'Mystery'],
    year: 2024,
    rating: 9.3,
    ratingCount: 198000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's10e1', number: 1, title: 'Silent Signal', description: 'The colony ship Prometheus goes dark, and Commander Shaw is sent to investigate.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/or1e1/320/180', rating: 9.2, airDate: '2024-09-06' },
          { id: 's10e2', number: 2, title: 'First Contact', description: 'The rescue team boards Prometheus and finds the colonists... changed.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/or1e2/320/180', rating: 9.4, airDate: '2024-09-13' },
          { id: 's10e3', number: 3, title: 'Evolution', description: 'Shaw discovers the colonists have developed abilities that defy known science.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/or1e3/320/180', rating: 9.5, airDate: '2024-09-20' },
          { id: 's10e4', number: 4, title: 'The Choice', description: 'The crew must decide: return to Earth or join the evolution.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/or1e4/320/180', rating: 9.6, airDate: '2024-09-27' },
        ],
      },
    ],
    cast: [
      { name: 'Idris Okonkwo', role: 'Commander Shaw', photo: 'https://picsum.photos/seed/cast36/100/100' },
      { name: 'Eva Green', role: 'Dr. Nova Chen', photo: 'https://picsum.photos/seed/cast37/100/100' },
      { name: 'Rami Malek', role: 'Prophet', photo: 'https://picsum.photos/seed/cast38/100/100' },
    ],
    status: 'Airing',
    studio: 'Cosmic Pictures',
    country: 'International',
    language: 'English',
    totalEpisodes: 4,
    featured: false,
    trending: true,
  },
  {
    id: 's11',
    title: 'Ember Falls',
    poster: 'https://picsum.photos/seed/emberfalls/400/600',
    backdrop: 'https://picsum.photos/seed/emberfallsbg/1200/680',
    description: 'In a small mountain town hiding a terrible secret, a wildfire threatens to expose decades of buried truths. As the flames close in, the townspeople must confront what they\'ve done — and what they\'re willing to do to survive.',
    genre: ['Thriller', 'Drama', 'Mystery'],
    year: 2024,
    rating: 8.8,
    ratingCount: 167000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's11e1', number: 1, title: 'Smoke Rising', description: 'The fire begins and so do the questions about what really happened at Ember Lodge.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/ef1e1/320/180', rating: 8.7, airDate: '2024-07-12' },
          { id: 's11e2', number: 2, title: 'Ashes to Ashes', description: 'A body is found in the fire zone, and all evidence points to the town\'s beloved sheriff.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/ef1e2/320/180', rating: 8.9, airDate: '2024-07-19' },
          { id: 's11e3', number: 3, title: 'Flashpoint', description: 'The truth about Ember Falls threatens to destroy the entire community.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/ef1e3/320/180', rating: 9.0, airDate: '2024-07-26' },
        ],
      },
    ],
    cast: [
      { name: 'Sarah Mitchell', role: 'Firefighter Kate', photo: 'https://picsum.photos/seed/cast39/100/100' },
      { name: 'Robert Taylor', role: 'Sheriff Hayes', photo: 'https://picsum.photos/seed/cast40/100/100' },
      { name: 'Mia Chang', role: 'Reporter Lisa', photo: 'https://picsum.photos/seed/cast41/100/100' },
    ],
    status: 'Completed',
    studio: 'Mountain View Films',
    country: 'United States',
    language: 'English',
    totalEpisodes: 3,
    featured: false,
    trending: false,
  },
  {
    id: 's12',
    title: 'Tokyo Drifters',
    poster: 'https://picsum.photos/seed/tokyodrifters/400/600',
    backdrop: 'https://picsum.photos/seed/tokyodriftersbg/1200/680',
    description: 'Three runaway teenagers form an underground racing crew in the neon-lit streets of Tokyo, competing against the city\'s most dangerous drivers. But when they uncover a human trafficking ring operating through the racing scene, the stakes become life and death.',
    genre: ['Action', 'Drama', 'Thriller'],
    year: 2024,
    rating: 8.4,
    ratingCount: 213000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's12e1', number: 1, title: 'Ignition', description: 'Three strangers meet at an illegal street race and form an instant connection.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/td1e1/320/180', rating: 8.3, airDate: '2024-03-15' },
          { id: 's12e2', number: 2, title: 'Red Line', description: 'The crew enters a high-stakes tournament that draws the attention of the Yakuza.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/td1e2/320/180', rating: 8.5, airDate: '2024-03-22' },
          { id: 's12e3', number: 3, title: 'Drift King', description: 'A legendary drifter offers to train the crew for the championship race.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/td1e3/320/180', rating: 8.6, airDate: '2024-03-29' },
          { id: 's12e4', number: 4, title: 'Nite Shift', description: 'The crew discovers the dark truth behind the racing empire.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/td1e4/320/180', rating: 8.8, airDate: '2024-04-05' },
        ],
      },
    ],
    cast: [
      { name: 'Takeshi Yamamoto', role: 'Kenji', photo: 'https://picsum.photos/seed/cast42/100/100' },
      { name: 'Lisa Park', role: 'Yuna', photo: 'https://picsum.photos/seed/cast43/100/100' },
      { name: 'Carlos Rivera', role: 'Marco', photo: 'https://picsum.photos/seed/cast44/100/100' },
    ],
    status: 'Completed',
    studio: 'Neon Valley Studios',
    country: 'Japan',
    language: 'Japanese',
    totalEpisodes: 4,
    featured: false,
    trending: false,
  },
  {
    id: 's13',
    title: 'El Ladrón de Sueños',
    poster: 'https://picsum.photos/seed/ladrondesuenos/400/600',
    backdrop: 'https://picsum.photos/seed/ladrondesuenosbg/1200/680',
    description: 'A master art thief in Barcelona assembles a team of specialists to steal a legendary painting hidden inside the vault of the most powerful family in Spain. But the heist reveals a conspiracy stretching back centuries, connecting stolen art to a secret society that has shaped European history from the shadows.',
    genre: ['Thriller', 'Drama', 'Mystery'],
    year: 2023,
    rating: 9.2,
    ratingCount: 215000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's13e1', number: 1, title: 'El Prólogo', description: 'Retired thief Mateo is pulled back into the game when an old ally offers the heist of a lifetime.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/ld1e1/320/180', rating: 9.1, airDate: '2023-06-02' },
          { id: 's13e2', number: 2, title: 'La Familia Vidal', description: 'The team infiltrates the Vidal estate and discovers the vault is more fortress than safe.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/ld1e2/320/180', rating: 9.3, airDate: '2023-06-09' },
          { id: 's13e3', number: 3, title: 'Pintura Sangrienta', description: 'A rival thief complicates the plan while secrets about the painting emerge.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ld1e3/320/180', rating: 9.2, airDate: '2023-06-16' },
          { id: 's13e4', number: 4, title: 'El Silencio', description: 'Inside the vault, Mateo discovers the painting hides a map to an even greater treasure.', duration: '61 min', thumbnail: 'https://picsum.photos/seed/ld1e4/320/180', rating: 9.4, airDate: '2023-06-23' },
          { id: 's13e5', number: 5, title: 'La Sociedad', description: 'The secret society reveals itself, and the heist becomes a fight for survival.', duration: '64 min', thumbnail: 'https://picsum.photos/seed/ld1e5/320/180', rating: 9.5, airDate: '2023-06-30' },
        ],
      },
    ],
    cast: [
      { name: 'Javier Gutiérrez', role: 'Mateo Reyes', photo: 'https://picsum.photos/seed/cast45/100/100' },
      { name: 'Penélope Cruz', role: 'Isabel Montero', photo: 'https://picsum.photos/seed/cast46/100/100' },
      { name: 'Miguel Ángel Silvestre', role: 'Leo Vidal', photo: 'https://picsum.photos/seed/cast47/100/100' },
      { name: 'Laia Manzanares', role: 'Carmen Ruiz', photo: 'https://picsum.photos/seed/cast48/100/100' },
    ],
    status: 'Completed',
    studio: 'Casa de Cine Madrid',
    country: 'Spain',
    language: 'Spanish',
    totalEpisodes: 5,
    featured: true,
    trending: true,
  },
  {
    id: 's14',
    title: 'La Couronne de Lumière',
    poster: 'https://picsum.photos/seed/couronnelumiere/400/600',
    backdrop: 'https://picsum.photos/seed/couronnelumierebg/1200/680',
    description: 'In 17th-century Versailles, a brilliant young woman disguised as a court painter uncovers a plot to poison the Queen. Navigating the treacherous politics of the Sun King\'s court, she must outwit powerful enemies while hiding her true identity from the man she secretly loves.',
    genre: ['Drama', 'History', 'Romance'],
    year: 2024,
    rating: 8.9,
    ratingCount: 178000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's14e1', number: 1, title: 'Le Tableau', description: 'Young artist Élise arrives at Versailles with a stolen invitation to join the court painters.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/cl1e1/320/180', rating: 8.8, airDate: '2024-01-08' },
          { id: 's14e2', number: 2, title: 'Le Masque', description: 'Élise paints the Queen\'s portrait and notices signs of poison in the royal household.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/cl1e2/320/180', rating: 9.0, airDate: '2024-01-15' },
          { id: 's14e3', number: 3, title: 'Le Complot', description: 'The conspiracy deepens as Élise discovers the poisoner is someone close to the throne.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/cl1e3/320/180', rating: 9.1, airDate: '2024-01-22' },
          { id: 's14e4', number: 4, title: 'La Danse', description: 'A grand ball becomes the setting for a dangerous game of cat and mouse.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/cl1e4/320/180', rating: 9.2, airDate: '2024-01-29' },
          { id: 's14e5', number: 5, title: 'Le Soleil et l\'Ombre', description: 'Élise\'s identity is threatened as the King himself takes an interest in her work.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/cl1e5/320/180', rating: 9.3, airDate: '2024-02-05' },
        ],
      },
    ],
    cast: [
      { name: 'Léa Seydoux', role: 'Élise D\'Arcy', photo: 'https://picsum.photos/seed/cast49/100/100' },
      { name: 'Gaspard Ulliel', role: 'Chevalier de Lune', photo: 'https://picsum.photos/seed/cast50/100/100' },
      { name: 'Eva Green', role: 'Reine Marie-Thérèse', photo: 'https://picsum.photos/seed/cast51/100/100' },
      { name: 'Pierre Niney', role: 'Roi Louis XIV', photo: 'https://picsum.photos/seed/cast52/100/100' },
      { name: 'Noémie Merlant', role: 'Marguerite', photo: 'https://picsum.photos/seed/cast53/100/100' },
    ],
    status: 'Completed',
    studio: 'Studio Parisien',
    country: 'France',
    language: 'French',
    totalEpisodes: 5,
    featured: true,
    trending: false,
  },
  {
    id: 's15',
    title: 'Iron Genesis',
    poster: 'https://picsum.photos/seed/irongenesis/400/600',
    backdrop: 'https://picsum.photos/seed/irongenesisbg/1200/680',
    description: 'In a post-apocalyptic Japan overrun by biomechanical beasts, a teenage mechanic discovers she can synchronize with an ancient mecha buried beneath Mount Fuji. As humanity\'s last line of defense, she must master the Iron Genesis while uncovering the truth about why the machines turned against their creators.',
    genre: ['Sci-Fi', 'Action', 'Fantasy'],
    year: 2024,
    rating: 9.5,
    ratingCount: 342000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's15e1', number: 1, title: 'Rust and Bone', description: 'Yuki discovers the dormant mecha while scavenging in the ruins of old Tokyo.', duration: '24 min', thumbnail: 'https://picsum.photos/seed/ig1e1/320/180', rating: 9.3, airDate: '2024-04-06' },
          { id: 's15e2', number: 2, title: 'First Sync', description: 'The neural link between Yuki and the mecha activates for the first time during a beast attack.', duration: '24 min', thumbnail: 'https://picsum.photos/seed/ig1e2/320/180', rating: 9.5, airDate: '2024-04-13' },
          { id: 's15e3', number: 3, title: 'The Architect', description: 'A mysterious stranger reveals he designed the mechas and knows why they rebelled.', duration: '24 min', thumbnail: 'https://picsum.photos/seed/ig1e3/320/180', rating: 9.4, airDate: '2024-04-20' },
          { id: 's15e4', number: 4, title: 'Iron Heart', description: 'Yuki faces a beast that can replicate the mecha\'s abilities, forcing her to adapt.', duration: '24 min', thumbnail: 'https://picsum.photos/seed/ig1e4/320/180', rating: 9.6, airDate: '2024-04-27' },
          { id: 's15e5', number: 5, title: 'Genesis Protocol', description: 'The truth about the mecha rebellion threatens to destroy what remains of humanity.', duration: '24 min', thumbnail: 'https://picsum.photos/seed/ig1e5/320/180', rating: 9.7, airDate: '2024-05-04' },
        ],
      },
    ],
    cast: [
      { name: 'Rie Takahashi', role: 'Yuki (voice)', photo: 'https://picsum.photos/seed/cast54/100/100' },
      { name: 'Yuichi Nakamura', role: 'Dr. Kuroda (voice)', photo: 'https://picsum.photos/seed/cast55/100/100' },
      { name: 'Saori Hayami', role: 'Sakura (voice)', photo: 'https://picsum.photos/seed/cast56/100/100' },
      { name: 'Kaito Ishikawa', role: 'Ren (voice)', photo: 'https://picsum.photos/seed/cast57/100/100' },
    ],
    status: 'Airing',
    studio: 'Titan Animation',
    country: 'Japan',
    language: 'Japanese',
    totalEpisodes: 5,
    featured: true,
    trending: true,
  },
  {
    id: 's16',
    title: 'Sangam',
    poster: 'https://picsum.photos/seed/sangamseries/400/600',
    backdrop: 'https://picsum.photos/seed/sangamseriesbg/1200/680',
    description: 'Three generations of the Mehta family in Mumbai clash over tradition and modernity when the youngest daughter announces she will run the family\'s century-old textile business instead of her arranged-marriage plans. As old secrets surface and new alliances form, the family must choose between the legacy they\'ve built and the future they deserve.',
    genre: ['Drama', 'Romance', 'Comedy'],
    year: 2023,
    rating: 8.7,
    ratingCount: 265000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's16e1', number: 1, title: 'The Thread', description: 'Priya Mehta shocks her family by rejecting her fiancé to take over the family business.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/sg1e1/320/180', rating: 8.6, airDate: '2023-08-04' },
          { id: 's16e2', number: 2, title: 'Old World', description: 'The patriarch reveals the true origins of the family business, involving a forbidden love story.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/sg1e2/320/180', rating: 8.8, airDate: '2023-08-11' },
          { id: 's16e3', number: 3, title: 'New Colors', description: 'Priya modernizes the textile mill while her grandmother shares her own revolutionary past.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/sg1e3/320/180', rating: 8.7, airDate: '2023-08-18' },
          { id: 's16e4', number: 4, title: 'Unraveled', description: 'A corporate takeover threat forces the family to unite despite their differences.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/sg1e4/320/180', rating: 8.9, airDate: '2023-08-25' },
          { id: 's16e5', number: 5, title: 'Woven Together', description: 'The season finale brings an unexpected twist that redefines what family means.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/sg1e5/320/180', rating: 9.0, airDate: '2023-09-01' },
        ],
      },
      {
        number: 2,
        year: '2024',
        episodes: [
          { id: 's16e6', number: 1, title: 'Silk Road', description: 'Priya expands the business internationally while facing resistance at home.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/sg2e1/320/180', rating: 8.8, airDate: '2024-03-08' },
          { id: 's16e7', number: 2, title: 'Family Ties', description: 'A long-lost relative returns with a claim that could upend everything.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/sg2e2/320/180', rating: 8.9, airDate: '2024-03-15' },
          { id: 's16e8', number: 3, title: 'The Wedding', description: 'The family gathers for a celebration that reveals deeper divisions and surprising bonds.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/sg2e3/320/180', rating: 9.1, airDate: '2024-03-22' },
        ],
      },
    ],
    cast: [
      { name: 'Priyanka Sharma', role: 'Priya Mehta', photo: 'https://picsum.photos/seed/cast58/100/100' },
      { name: 'Amitabh Ranganathan', role: 'Bapuji Mehta', photo: 'https://picsum.photos/seed/cast59/100/100' },
      { name: 'Deepika Iyer', role: 'Ananya Mehta', photo: 'https://picsum.photos/seed/cast60/100/100' },
      { name: 'Vikram Singh', role: 'Rohan Kapoor', photo: 'https://picsum.photos/seed/cast61/100/100' },
    ],
    status: 'Completed',
    studio: 'Mumbai Dreams Productions',
    country: 'India',
    language: 'Hindi',
    totalEpisodes: 8,
    featured: false,
    trending: true,
  },
  {
    id: 's17',
    title: 'Frostbite',
    poster: 'https://picsum.photos/seed/frostbiteseries/400/600',
    backdrop: 'https://picsum.photos/seed/frostbiteseriesbg/1200/680',
    description: 'In the frozen wilderness of northern Norway, detective Erik Solberg investigates a series of ritualistic murders that mirror ancient Viking sacrifices. As the body count rises and the polar night descends, Erik realizes the killer is reenacting a prophecy that foretells the end of the world.',
    genre: ['Mystery', 'Thriller', 'Horror'],
    year: 2023,
    rating: 9.1,
    ratingCount: 195000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's17e1', number: 1, title: 'The First Frost', description: 'A body is found arranged in a Viking burial formation on the frozen lake outside Tromsø.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/fb1e1/320/180', rating: 9.0, airDate: '2023-11-03' },
          { id: 's17e2', number: 2, title: 'Polar Night', description: 'As darkness consumes the town for weeks, a second body appears with runic carvings.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/fb1e2/320/180', rating: 9.2, airDate: '2023-11-10' },
          { id: 's17e3', number: 3, title: 'Ragnarök', description: 'Erik decodes the runes and realizes the killer believes they are fulfilling an ancient prophecy.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/fb1e3/320/180', rating: 9.3, airDate: '2023-11-17' },
          { id: 's17e4', number: 4, title: 'The Seer', description: 'A local shaman reveals the prophecy\'s final act and a shocking connection to Erik\'s past.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/fb1e4/320/180', rating: 9.4, airDate: '2023-11-24' },
        ],
      },
    ],
    cast: [
      { name: 'Stellan Skarsgård', role: 'Detective Erik Solberg', photo: 'https://picsum.photos/seed/cast62/100/100' },
      { name: 'Noomi Rapace', role: 'Dr. Astrid Henriksen', photo: 'https://picsum.photos/seed/cast63/100/100' },
      { name: 'Kristofer Hivju', role: 'The Shaman', photo: 'https://picsum.photos/seed/cast64/100/100' },
      { name: 'Ine Wiro Saban', role: 'Officer Liv Dahl', photo: 'https://picsum.photos/seed/cast65/100/100' },
    ],
    status: 'Completed',
    studio: 'Nordisk Film',
    country: 'Norway',
    language: 'Norwegian',
    totalEpisodes: 4,
    featured: true,
    trending: true,
  },
  {
    id: 's18',
    title: 'Morro do Sol',
    poster: 'https://picsum.photos/seed/morrodosol/400/600',
    backdrop: 'https://picsum.photos/seed/morrodosolbg/1200/680',
    description: 'In the vibrant but dangerous favelas of Rio de Janeiro, a teenage girl with a gift for numbers becomes the accountant for the neighborhood\'s most powerful drug lord while secretly funneling money to build a school. When a federal investigation threatens to expose both worlds, she must decide which dream is worth sacrificing.',
    genre: ['Drama', 'Thriller', 'Action'],
    year: 2024,
    rating: 9.0,
    ratingCount: 188000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's18e1', number: 1, title: 'Os Números', description: 'Fifteen-year-old Luana impresses the local boss with her uncanny ability with numbers.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/ms1e1/320/180', rating: 8.9, airDate: '2024-02-09' },
          { id: 's18e2', number: 2, title: 'Double Life', description: 'Luana begins skimming profits to fund her secret school project in the community center.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/ms1e2/320/180', rating: 9.0, airDate: '2024-02-16' },
          { id: 's18e3', number: 3, title: 'O Chefão', description: 'The drug lord begins to suspect someone is diverting funds and sends his enforcer.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/ms1e3/320/180', rating: 9.1, airDate: '2024-02-23' },
          { id: 's18e4', number: 4, title: 'Federal', description: 'Federal agents raid the favela, and Luana is caught between two dangerous worlds.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ms1e4/320/180', rating: 9.2, airDate: '2024-03-01' },
          { id: 's18e5', number: 5, title: 'Sol Nascente', description: 'In the explosive finale, Luana makes a choice that transforms the entire community.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/ms1e5/320/180', rating: 9.4, airDate: '2024-03-08' },
        ],
      },
    ],
    cast: [
      { name: 'Sophie Charlotte', role: 'Luana', photo: 'https://picsum.photos/seed/cast66/100/100' },
      { name: 'Bruno Gagliasso', role: 'Doutor', photo: 'https://picsum.photos/seed/cast67/100/100' },
      { name: 'Seu Jorge', role: 'Tio Zeca', photo: 'https://picsum.photos/seed/cast68/100/100' },
      { name: 'Taís Araújo', role: 'Detetive Fernanda', photo: 'https://picsum.photos/seed/cast69/100/100' },
    ],
    status: 'Completed',
    studio: 'Globo Filmes',
    country: 'Brazil',
    language: 'Portuguese',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's19',
    title: 'Zeitgeber',
    poster: 'https://picsum.photos/seed/zeitgebertv/400/600',
    backdrop: 'https://picsum.photos/seed/zeitgebertvbg/1200/680',
    description: 'A quantum physicist in Berlin accidentally creates a time loop that traps her entire apartment building in a repeating 24-hour cycle. As she tries to solve the paradox, she discovers each loop reveals different truths about her neighbors — and that someone else in the building has been manipulating time long before she arrived.',
    genre: ['Sci-Fi', 'Mystery', 'Thriller'],
    year: 2024,
    rating: 9.3,
    ratingCount: 256000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's19e1', number: 1, title: '00:00', description: 'Dr. Lena Vogt realizes she is living the same day over and over in her Berlin apartment.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/zg1e1/320/180', rating: 9.2, airDate: '2024-05-03' },
          { id: 's19e2', number: 2, title: '12:00', description: 'Lena discovers her neighbor Herr Klein has been keeping a journal of every repeated day.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/zg1e2/320/180', rating: 9.3, airDate: '2024-05-10' },
          { id: 's19e3', number: 3, title: '18:00', description: 'The time loop begins to fracture, showing glimpses of a catastrophic event at midnight.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/zg1e3/320/180', rating: 9.4, airDate: '2024-05-17' },
          { id: 's19e4', number: 4, title: '23:59', description: 'Lena confronts the time manipulator and learns the loop was created to prevent something worse.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/zg1e4/320/180', rating: 9.5, airDate: '2024-05-24' },
        ],
      },
    ],
    cast: [
      { name: 'Nina Hoss', role: 'Dr. Lena Vogt', photo: 'https://picsum.photos/seed/cast70/100/100' },
      { name: 'Daniel Brühl', role: 'Herr Klein', photo: 'https://picsum.photos/seed/cast71/100/100' },
      { name: 'Marta Nieto', role: 'Elara', photo: 'https://picsum.photos/seed/cast72/100/100' },
      { name: 'Jürgen Vogel', role: 'Prof. Brandt', photo: 'https://picsum.photos/seed/cast73/100/100' },
    ],
    status: 'Completed',
    studio: 'UFA Fiction',
    country: 'Germany',
    language: 'German',
    totalEpisodes: 4,
    featured: true,
    trending: true,
  },
  {
    id: 's20',
    title: 'Red Dust',
    poster: 'https://picsum.photos/seed/reddusttv/400/600',
    backdrop: 'https://picsum.photos/seed/reddusttvbg/1200/680',
    description: 'After a small plane crashes in the unforgiving Australian outback, a group of strangers must survive extreme heat, scarce water, and each other. But when they discover the wreckage contains something that powerful people will kill to recover, survival becomes a deadly game of cat and mouse across the red desert.',
    genre: ['Thriller', 'Action', 'Drama'],
    year: 2023,
    rating: 8.6,
    ratingCount: 142000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's20e1', number: 1, title: 'Down Under', description: 'A chartered flight goes down in the remote Pilbara region with six survivors.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/rd1e1/320/180', rating: 8.5, airDate: '2023-07-07' },
          { id: 's20e2', number: 2, title: 'Dry Season', description: 'Water runs out and tensions flare as the group argues over the best escape route.', duration: '48 min', thumbnail: 'https://picsum.photos/seed/rd1e2/320/180', rating: 8.6, airDate: '2023-07-14' },
          { id: 's20e3', number: 3, title: 'The Package', description: 'They discover the plane was carrying a sealed case that someone desperately wants back.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/rd1e3/320/180', rating: 8.7, airDate: '2023-07-21' },
          { id: 's20e4', number: 4, title: 'Hunters', description: 'Armed mercenaries arrive in the outback, and the survivors realize they are the prey.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/rd1e4/320/180', rating: 8.8, airDate: '2023-07-28' },
          { id: 's20e5', number: 5, title: 'Uluru', description: 'The final chase leads to the sacred rock as secrets are revealed and sacrifices made.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/rd1e5/320/180', rating: 9.0, airDate: '2023-08-04' },
        ],
      },
    ],
    cast: [
      { name: 'Eric Bana', role: 'Jack Callahan', photo: 'https://picsum.photos/seed/cast74/100/100' },
      { name: 'Cate Blanchett', role: 'Dr. Sarah Mitchell', photo: 'https://picsum.photos/seed/cast75/100/100' },
      { name: 'David Wenham', role: 'The Pilot', photo: 'https://picsum.photos/seed/cast76/100/100' },
      { name: 'Deborah Mailman', role: 'Officer Williams', photo: 'https://picsum.photos/seed/cast77/100/100' },
    ],
    status: 'Completed',
    studio: 'Madman Entertainment',
    country: 'Australia',
    language: 'English',
    totalEpisodes: 5,
    featured: false,
    trending: false,
  },
  {
    id: 's21',
    title: 'İstanbul\'un Gözyaşları',
    poster: 'https://picsum.photos/seed/istanbulgozyaslari/400/600',
    backdrop: 'https://picsum.photos/seed/istanbulgozyaslaribg/1200/680',
    description: 'In 16th-century Istanbul, a brilliant Ottoman princess falls in love with a Venetian ambassador\'s son, setting off a chain of events that threatens the fragile peace between two great empires. Their forbidden love story unfolds against a backdrop of palace intrigue, naval battles, and the breathtaking beauty of the Bosphorus.',
    genre: ['Romance', 'History', 'Drama'],
    year: 2024,
    rating: 8.8,
    ratingCount: 310000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's21e1', number: 1, title: 'The Bosphorus', description: 'Princess Esma first encounters Marco during a diplomatic reception at Topkapi Palace.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/ig1e1/320/180', rating: 8.7, airDate: '2024-03-15' },
          { id: 's21e2', number: 2, title: 'The Grand Bazaar', description: 'A secret meeting in the labyrinth of the Grand Bazaar deepens their connection.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/ig1e2/320/180', rating: 8.8, airDate: '2024-03-22' },
          { id: 's21e3', number: 3, title: 'The Harem', description: 'Esma\'s rival in the harem discovers the affair and schemes to expose it.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/ig1e3/320/180', rating: 8.9, airDate: '2024-03-29' },
          { id: 's21e4', number: 4, title: 'War Ships', description: 'A Venetian fleet arrives at Istanbul, and Marco is caught between love and duty.', duration: '68 min', thumbnail: 'https://picsum.photos/seed/ig1e4/320/180', rating: 9.0, airDate: '2024-04-05' },
          { id: 's21e5', number: 5, title: 'The Tulip Era', description: 'The season concludes with a dramatic choice that will reshape both empires.', duration: '72 min', thumbnail: 'https://picsum.photos/seed/ig1e5/320/180', rating: 9.1, airDate: '2024-04-12' },
        ],
      },
    ],
    cast: [
      { name: 'Burak Özçivit', role: 'Marco Bellini', photo: 'https://picsum.photos/seed/cast78/100/100' },
      { name: 'Tuba Büyüküstün', role: 'Princess Esma', photo: 'https://picsum.photos/seed/cast79/100/100' },
      { name: 'Halit Ergenç', role: 'Sultan Murad', photo: 'https://picsum.photos/seed/cast80/100/100' },
      { name: 'Beren Saat', role: 'Mahidevran', photo: 'https://picsum.photos/seed/cast81/100/100' },
    ],
    status: 'Completed',
    studio: 'Ay Yapım',
    country: 'Turkey',
    language: 'Turkish',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's22',
    title: 'Dragon Vein',
    poster: 'https://picsum.photos/seed/dragonvein/400/600',
    backdrop: 'https://picsum.photos/seed/dragonveinbg/1200/680',
    description: 'In ancient China, a wandering swordsman with no memory of his past discovers he is the last heir of the Dragon Vein clan — masters of a martial art so powerful it was erased from history. As rival clans and imperial forces hunt him, he must recover his memories and unite the scattered disciples before a dark sorcerer reawakens an ancient evil.',
    genre: ['Action', 'Fantasy', 'History'],
    year: 2024,
    rating: 9.4,
    ratingCount: 380000,
    maturity: 'TV-14',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's22e1', number: 1, title: 'The Nameless Blade', description: 'A swordsman with no memory arrives at a remote monastery seeking answers.', duration: '45 min', thumbnail: 'https://picsum.photos/seed/dv1e1/320/180', rating: 9.3, airDate: '2024-06-14' },
          { id: 's22e2', number: 2, title: 'The Five Clans', description: 'Assassins from five rival clans attack simultaneously, confirming the swordsman\'s identity.', duration: '46 min', thumbnail: 'https://picsum.photos/seed/dv1e2/320/180', rating: 9.4, airDate: '2024-06-21' },
          { id: 's22e3', number: 3, title: 'Iron Lotus', description: 'The swordsman finds a master who teaches him the first form of the Dragon Vein technique.', duration: '48 min', thumbnail: 'https://picsum.photos/seed/dv1e3/320/180', rating: 9.5, airDate: '2024-06-28' },
          { id: 's22e4', number: 4, title: 'The Emperor\'s Shadow', description: 'Imperial guards capture the swordsman, revealing a connection to the royal bloodline.', duration: '47 min', thumbnail: 'https://picsum.photos/seed/dv1e4/320/180', rating: 9.4, airDate: '2024-07-05' },
          { id: 's22e5', number: 5, title: 'Awakening', description: 'The swordsman\'s memories return, along with the terrible truth of why they were erased.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/dv1e5/320/180', rating: 9.6, airDate: '2024-07-12' },
          { id: 's22e6', number: 6, title: 'Dragon Rising', description: 'The dark sorcerer begins his ritual, and the final battle for the martial arts world begins.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/dv1e6/320/180', rating: 9.7, airDate: '2024-07-19' },
        ],
      },
    ],
    cast: [
      { name: 'Wu Jing', role: 'The Swordsman / Long Wei', photo: 'https://picsum.photos/seed/cast82/100/100' },
      { name: 'Zhang Ziyi', role: 'Master Mei', photo: 'https://picsum.photos/seed/cast83/100/100' },
      { name: 'Donnie Yen', role: 'Dark Sorcerer Xuan', photo: 'https://picsum.photos/seed/cast84/100/100' },
      { name: 'Fan Bingbing', role: 'Empress Lin', photo: 'https://picsum.photos/seed/cast85/100/100' },
      { name: 'Wang Yibo', role: 'Disciple Feng', photo: 'https://picsum.photos/seed/cast86/100/100' },
    ],
    status: 'Airing',
    studio: 'iQiyi Studios',
    country: 'China',
    language: 'Mandarin',
    totalEpisodes: 6,
    featured: true,
    trending: true,
  },
  {
    id: 's23',
    title: 'Cuore di Roma',
    poster: 'https://picsum.photos/seed/cuorediroma/400/600',
    backdrop: 'https://picsum.photos/seed/cuorediromabg/1200/680',
    description: 'A fiery young chef from Naples inherits a crumbling trattoria in the heart of Rome and discovers it was once the most celebrated kitchen in Italy. As she restores the restaurant to its former glory, she uncovers her grandmother\'s secret recipes and the love story that inspired them, one dish at a time.',
    genre: ['Drama', 'Romance', 'Comedy'],
    year: 2023,
    rating: 8.5,
    ratingCount: 156000,
    maturity: 'TV-PG',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's23e1', number: 1, title: 'L\'Eredità', description: 'Giulia arrives in Rome to find her grandmother\'s trattoria in disrepair but full of memories.', duration: '48 min', thumbnail: 'https://picsum.photos/seed/cr1e1/320/180', rating: 8.4, airDate: '2023-09-08' },
          { id: 's23e2', number: 2, title: 'Pasta eTradizione', description: 'Giulia attempts her grandmother\'s legendary pasta recipe but struggles to recreate the magic.', duration: '46 min', thumbnail: 'https://picsum.photos/seed/cr1e2/320/180', rating: 8.5, airDate: '2023-09-15' },
          { id: 's23e3', number: 3, title: 'Il Rival', description: 'A snooty Michelin-starred chef opens next door and challenges Giulia to a public cook-off.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/cr1e3/320/180', rating: 8.7, airDate: '2023-09-22' },
          { id: 's23e4', number: 4, title: 'Amore e Aglio', description: 'A charming food critic becomes both Giulia\'s greatest ally and her biggest distraction.', duration: '49 min', thumbnail: 'https://picsum.photos/seed/cr1e4/320/180', rating: 8.6, airDate: '2023-09-29' },
        ],
      },
    ],
    cast: [
      { name: 'Gaia Girace', role: 'Giulia Esposito', photo: 'https://picsum.photos/seed/cast87/100/100' },
      { name: 'Stefano Accorsi', role: 'Food Critic Marco', photo: 'https://picsum.photos/seed/cast88/100/100' },
      { name: 'Monica Bellucci', role: 'Nonna Rosa (flashbacks)', photo: 'https://picsum.photos/seed/cast89/100/100' },
    ],
    status: 'Completed',
    studio: 'Cinecittà Studios',
    country: 'Italy',
    language: 'Italian',
    totalEpisodes: 4,
    featured: false,
    trending: false,
  },
  {
    id: 's24',
    title: 'Frontera Roja',
    poster: 'https://picsum.photos/seed/fronteraroja/400/600',
    backdrop: 'https://picsum.photos/seed/fronterarojabg/1200/680',
    description: 'A decorated DEA agent goes undercover inside Mexico\'s most ruthless cartel and discovers the organization has infiltrated the highest levels of both governments. As the lines between lawman and criminal blur, he must navigate a world where trust is lethal and the wrong move costs lives — including his own family\'s.',
    genre: ['Action', 'Thriller', 'Drama'],
    year: 2024,
    rating: 9.1,
    ratingCount: 298000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's24e1', number: 1, title: 'La Frontera', description: 'Agent Carlos Vega crosses into Mexico under a new identity to infiltrate the Sinaloa cartel.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/fr1e1/320/180', rating: 9.0, airDate: '2024-08-02' },
          { id: 's24e2', number: 2, title: 'El Narco', description: 'Carlos earns the cartel boss\'s trust by executing a high-risk operation.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/fr1e2/320/180', rating: 9.1, airDate: '2024-08-09' },
          { id: 's24e3', number: 3, title: 'Sangre por Sangre', description: 'A rival cartel attack forces Carlos to make a choice that violates everything he believes.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/fr1e3/320/180', rating: 9.2, airDate: '2024-08-16' },
          { id: 's24e4', number: 4, title: 'El Fantasma', description: 'Carlos discovers the cartel has an asset inside the DEA, making him question his mission.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/fr1e4/320/180', rating: 9.3, airDate: '2024-08-23' },
          { id: 's24e5', number: 5, title: 'Juicio Final', description: 'The operation unravels as Carlos\'s cover is threatened and his family becomes a target.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/fr1e5/320/180', rating: 9.5, airDate: '2024-08-30' },
        ],
      },
    ],
    cast: [
      { name: 'Diego Luna', role: 'Agent Carlos Vega', photo: 'https://picsum.photos/seed/cast90/100/100' },
      { name: 'Gael García Bernal', role: 'El Chapo Jr.', photo: 'https://picsum.photos/seed/cast91/100/100' },
      { name: 'Stephanie Salas', role: 'Maria Vega', photo: 'https://picsum.photos/seed/cast92/100/100' },
      { name: 'Damian Alcazar', role: 'Don Hector', photo: 'https://picsum.photos/seed/cast93/100/100' },
    ],
    status: 'Airing',
    studio: 'Televisa Studios',
    country: 'Mexico',
    language: 'Spanish',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's25',
    title: 'Theasset',
    poster: 'https://picsum.photos/seed/theasset/400/600',
    backdrop: 'https://picsum.photos/seed/theassetbg/1200/680',
    description: 'When a Russian defector arrives in London with evidence of a mole inside MI6, veteran spy Catherine Hyde is given 72 hours to identify the traitor before the intelligence is leaked to Moscow. But as she interrogates suspects in a locked-down safehouse, she realizes the defector may not be who they claim — and the real game has only just begun.',
    genre: ['Thriller', 'Mystery', 'Drama'],
    year: 2022,
    rating: 9.0,
    ratingCount: 224000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2022',
        episodes: [
          { id: 's25e1', number: 1, title: 'The Defector', description: 'A Russian intelligence officer walks into the British embassy in Istanbul claiming to have critical information.', duration: '56 min', thumbnail: 'https://picsum.photos/seed/ta1e1/320/180', rating: 8.9, airDate: '2022-10-07' },
          { id: 's25e2', number: 2, title: 'Safehouse', description: 'Catherine assembles a team and begins interrogating five MI6 officers under suspicion.', duration: '54 min', thumbnail: 'https://picsum.photos/seed/ta1e2/320/180', rating: 9.1, airDate: '2022-10-14' },
          { id: 's25e3', number: 3, title: 'Double Cross', description: 'One suspect is found dead, and evidence points to an inside job within the investigation itself.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ta1e3/320/180', rating: 9.2, airDate: '2022-10-21' },
          { id: 's25e4', number: 4, title: 'The Pawn', description: 'Catherine uncovers the defector\'s true identity and realizes Moscow has been playing a longer game.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/ta1e4/320/180', rating: 9.3, airDate: '2022-10-28' },
          { id: 's25e5', number: 5, title: 'Checkmate', description: 'In a tense finale, the mole is revealed and the cost of the betrayal becomes devastatingly clear.', duration: '64 min', thumbnail: 'https://picsum.photos/seed/ta1e5/320/180', rating: 9.4, airDate: '2022-11-04' },
        ],
      },
      {
        number: 2,
        year: '2023',
        episodes: [
          { id: 's25e6', number: 1, title: 'Ghost Station', description: 'Catherine is sent to Vienna to extract an asset from a Russian black site.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/ta2e1/320/180', rating: 9.0, airDate: '2023-04-07' },
          { id: 's25e7', number: 2, title: 'Vienna Blood', description: 'The operation goes wrong and Catherine must go rogue to complete the mission.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/ta2e2/320/180', rating: 9.2, airDate: '2023-04-14' },
          { id: 's25e8', number: 3, title: 'The Exchange', description: 'A prisoner exchange at the Berlin Wall remnant site becomes the setting for a deadly confrontation.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/ta2e3/320/180', rating: 9.3, airDate: '2023-04-21' },
        ],
      },
    ],
    cast: [
      { name: 'Olivia Colman', role: 'Catherine Hyde', photo: 'https://picsum.photos/seed/cast94/100/100' },
      { name: 'Tom Hiddleston', role: 'Agent Whitmore', photo: 'https://picsum.photos/seed/cast95/100/100' },
      { name: 'Ralph Fiennes', role: 'The Defector', photo: 'https://picsum.photos/seed/cast96/100/100' },
      { name: 'Fiona Shaw', role: 'Director Hartley', photo: 'https://picsum.photos/seed/cast97/100/100' },
      { name: 'Andrew Scott', role: 'Agent Mercer', photo: 'https://picsum.photos/seed/cast98/100/100' },
    ],
    status: 'Completed',
    studio: 'BBC One',
    country: 'United Kingdom',
    language: 'English',
    totalEpisodes: 8,
    featured: false,
    trending: true,
  },
  {
    id: 's26',
    title: 'Seoul of the Dead',
    poster: 'https://picsum.photos/seed/seoulofthedead/400/600',
    backdrop: 'https://picsum.photos/seed/seoulofthedeadbg/1200/680',
    description: 'When a mysterious virus transforms half of Seoul into rabid creatures overnight, a group of survivors barricade themselves inside a luxury department store in Gangnam. With resources dwindling and the infected evolving, they must venture into the hellscape of the city to find a cure — or become the very monsters they\'re hiding from.',
    genre: ['Horror', 'Action', 'Thriller'],
    year: 2023,
    rating: 9.2,
    ratingCount: 420000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's26e1', number: 1, title: 'Day Zero', description: 'An unexplained outbreak in central Seoul spreads faster than anyone could anticipate.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/sd1e1/320/180', rating: 9.1, airDate: '2023-12-01' },
          { id: 's26e2', number: 2, title: 'The Department Store', description: 'Six strangers find each other in a Gangnam department store and establish a fragile alliance.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/sd1e2/320/180', rating: 9.2, airDate: '2023-12-08' },
          { id: 's26e3', number: 3, title: 'Evolution', description: 'The infected begin exhibiting new behaviors, suggesting they are learning and adapting.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/sd1e3/320/180', rating: 9.3, airDate: '2023-12-15' },
          { id: 's26e4', number: 4, title: 'The Cure', description: 'A scientist among the survivors believes the answer lies in the patient zero at Seoul National Hospital.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/sd1e4/320/180', rating: 9.4, airDate: '2023-12-22' },
          { id: 's26e5', number: 5, title: 'Gangnam Falls', description: 'The store is breached and the survivors must flee into the underground subway system.', duration: '65 min', thumbnail: 'https://picsum.photos/seed/sd1e5/320/180', rating: 9.5, airDate: '2023-12-29' },
        ],
      },
    ],
    cast: [
      { name: 'Ma Dong-seok', role: 'Sergeant Park', photo: 'https://picsum.photos/seed/cast99/100/100' },
      { name: 'Park So-dam', role: 'Dr. Yoon', photo: 'https://picsum.photos/seed/cast100/100/100' },
      { name: 'Choi Woo-shik', role: 'Delivery Driver Jin', photo: 'https://picsum.photos/seed/cast101/100/100' },
      { name: 'Jeon Yeo-been', role: 'Nurse Hye-won', photo: 'https://picsum.photos/seed/cast102/100/100' },
    ],
    status: 'Completed',
    studio: 'Studio Dragon',
    country: 'South Korea',
    language: 'Korean',
    totalEpisodes: 5,
    featured: true,
    trending: true,
  },
  {
    id: 's27',
    title: 'The Lost Trail',
    poster: 'https://picsum.photos/seed/losttrail/400/600',
    backdrop: 'https://picsum.photos/seed/losttrailbg/1200/680',
    description: 'A search-and-rescue expert in the Canadian Rockies is called to find a missing group of hikers and discovers they stumbled upon an abandoned research facility hidden deep in the mountains. The facility holds experiments that were meant to be destroyed decades ago — experiments that are still very much alive.',
    genre: ['Mystery', 'Thriller', 'Horror'],
    year: 2024,
    rating: 8.3,
    ratingCount: 125000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's27e1', number: 1, title: 'The Call', description: 'Wilderness expert Sam receives a distress signal from deep in Banff National Park.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/lt1e1/320/180', rating: 8.2, airDate: '2024-09-13' },
          { id: 's27e2', number: 2, title: 'The Facility', description: 'Sam finds the hikers trapped inside a derelict government research station.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/lt1e2/320/180', rating: 8.4, airDate: '2024-09-20' },
          { id: 's27e3', number: 3, title: 'Cold Science', description: 'The group discovers the facility was conducting experiments on hibernation that went horribly wrong.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/lt1e3/320/180', rating: 8.5, airDate: '2024-09-27' },
          { id: 's27e4', number: 4, title: 'The Subjects', description: 'The original test subjects are still alive, changed, and hunting through the facility.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/lt1e4/320/180', rating: 8.6, airDate: '2024-10-04' },
        ],
      },
    ],
    cast: [
      { name: 'Ryan Reynolds', role: 'Sam Croft', photo: 'https://picsum.photos/seed/cast103/100/100' },
      { name: 'Ellen Page', role: 'Dr. Emily Shaw', photo: 'https://picsum.photos/seed/cast104/100/100' },
      { name: 'Graham Greene', role: 'Elder Thomas', photo: 'https://picsum.photos/seed/cast105/100/100' },
    ],
    status: 'Completed',
    studio: 'Crave Originals',
    country: 'Canada',
    language: 'English',
    totalEpisodes: 4,
    featured: false,
    trending: false,
  },
  {
    id: 's28',
    title: 'Кровь и Лёд',
    poster: 'https://picsum.photos/seed/bloodandice/400/600',
    backdrop: 'https://picsum.photos/seed/bloodandicebg/1200/680',
    description: 'A celebrated Moscow psychiatrist begins treating a patient who claims to have committed murders that match unsolved cases from the past twenty years. As she digs deeper into his mind, she discovers he may be telling the truth — and that her own memories of the past may not be what they seem.',
    genre: ['Thriller', 'Mystery', 'Drama'],
    year: 2023,
    rating: 8.9,
    ratingCount: 167000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2023',
        episodes: [
          { id: 's28e1', number: 1, title: 'The Patient', description: 'Dr. Natasha Volkov takes on a new patient at the prestigious Moscow Institute of Psychology.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/bi1e1/320/180', rating: 8.8, airDate: '2023-04-07' },
          { id: 's28e2', number: 2, title: 'Confession', description: 'The patient begins describing murders with details only the killer could know.', duration: '53 min', thumbnail: 'https://picsum.photos/seed/bi1e2/320/180', rating: 9.0, airDate: '2023-04-14' },
          { id: 's28e3', number: 3, title: 'The Mirror', description: 'Natasha investigates and finds the murders match cases she worked on as a police consultant.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/bi1e3/320/180', rating: 9.1, airDate: '2023-04-21' },
          { id: 's28e4', number: 4, title: 'Lost Time', description: 'Natasha discovers gaps in her own memory that coincide with the murder dates.', duration: '60 min', thumbnail: 'https://picsum.photos/seed/bi1e4/320/180', rating: 9.2, airDate: '2023-04-28' },
          { id: 's28e5', number: 5, title: 'The Freeze', description: 'The devastating truth about Natasha\'s connection to the killings is finally revealed.', duration: '63 min', thumbnail: 'https://picsum.photos/seed/bi1e5/320/180', rating: 9.3, airDate: '2023-05-05' },
        ],
      },
    ],
    cast: [
      { name: 'Svetlana Khodchenkova', role: 'Dr. Natasha Volkov', photo: 'https://picsum.photos/seed/cast106/100/100' },
      { name: 'Danila Kozlovsky', role: 'The Patient / Dmitri', photo: 'https://picsum.photos/seed/cast107/100/100' },
      { name: 'Konstantin Khabensky', role: 'Detective Morozov', photo: 'https://picsum.photos/seed/cast108/100/100' },
      { name: 'Helena Bonham Carter', role: 'Prof. White', photo: 'https://picsum.photos/seed/cast109/100/100' },
    ],
    status: 'Completed',
    studio: 'Kinopoisk Studios',
    country: 'Russia',
    language: 'Russian',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's29',
    title: 'Hollow Creek',
    poster: 'https://picsum.photos/seed/hollowcreek/400/600',
    backdrop: 'https://picsum.photos/seed/hollowcreekbg/1200/680',
    description: 'After a family moves into a historic plantation house in rural Virginia, their teenage daughter begins communicating with the spirits of enslaved people who died on the property. As the manifestations grow violent, the family discovers the house was built on a gateway between the living and the dead — and something ancient is trying to come through.',
    genre: ['Horror', 'Mystery', 'Drama'],
    year: 2024,
    rating: 8.8,
    ratingCount: 195000,
    maturity: 'TV-MA',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's29e1', number: 1, title: 'The House', description: 'The Marshall family moves into Hollow Creek Plantation, unaware of its dark history.', duration: '52 min', thumbnail: 'https://picsum.photos/seed/hc1e1/320/180', rating: 8.7, airDate: '2024-10-04' },
          { id: 's29e2', number: 2, title: 'The Voices', description: 'Sixteen-year-old Maya begins hearing whispers and seeing figures in the family graveyard.', duration: '50 min', thumbnail: 'https://picsum.photos/seed/hc1e2/320/180', rating: 8.9, airDate: '2024-10-11' },
          { id: 's29e3', number: 3, title: 'The Archive', description: 'Maya discovers a hidden cellar filled with records of the enslaved people who lived and died here.', duration: '55 min', thumbnail: 'https://picsum.photos/seed/hc1e3/320/180', rating: 9.0, airDate: '2024-10-18' },
          { id: 's29e4', number: 4, title: 'The Gateway', description: 'The paranormal activity intensifies as a ritual opens a portal to the spirit world.', duration: '58 min', thumbnail: 'https://picsum.photos/seed/hc1e4/320/180', rating: 9.1, airDate: '2024-10-25' },
          { id: 's29e5', number: 5, title: 'The Crossing', description: 'Maya must find a way to close the gateway before an ancient entity crosses over.', duration: '62 min', thumbnail: 'https://picsum.photos/seed/hc1e5/320/180', rating: 9.3, airDate: '2024-11-01' },
        ],
      },
    ],
    cast: [
      { name: 'Jenna Ortega', role: 'Maya Marshall', photo: 'https://picsum.photos/seed/cast110/100/100' },
      { name: 'Jonathan Majors', role: 'Father David Marshall', photo: 'https://picsum.photos/seed/cast111/100/100' },
      { name: 'Viola Davis', role: 'Professor Adeline', photo: 'https://picsum.photos/seed/cast112/100/100' },
      { name: 'Amandla Stenberg', role: 'Spirit Guide Nia', photo: 'https://picsum.photos/seed/cast113/100/100' },
    ],
    status: 'Airing',
    studio: 'Blumhouse Television',
    country: 'United States',
    language: 'English',
    totalEpisodes: 5,
    featured: false,
    trending: true,
  },
  {
    id: 's30',
    title: 'Bangkok Blossoms',
    poster: 'https://picsum.photos/seed/bangkokblossoms/400/600',
    backdrop: 'https://picsum.photos/seed/bangkokblossomsbg/1200/680',
    description: 'A cheerful florist in Bangkok who can see the romantic aura of everyone she meets has never been in love herself. When a grumpy food critic from New York arrives to review her sister\'s restaurant, their clashing worlds create chaos, comedy, and an unexpected connection that neither saw coming.',
    genre: ['Romance', 'Comedy'],
    year: 2024,
    rating: 8.5,
    ratingCount: 234000,
    maturity: 'TV-PG',
    seasons: [
      {
        number: 1,
        year: '2024',
        episodes: [
          { id: 's30e1', number: 1, title: 'The Flower Shop', description: 'Kanya\'s peaceful life running her grandfather\'s flower shop is disrupted by a grumpy American.', duration: '45 min', thumbnail: 'https://picsum.photos/seed/bb1e1/320/180', rating: 8.4, airDate: '2024-05-17' },
          { id: 's30e2', number: 2, title: 'The Review', description: 'Michael\'s scathing review of her sister\'s restaurant sparks a war between the two siblings.', duration: '44 min', thumbnail: 'https://picsum.photos/seed/bb1e2/320/180', rating: 8.5, airDate: '2024-05-24' },
          { id: 's30e3', number: 3, title: 'The Aura', description: 'Kanya\'s gift shows her a surprising connection between Michael and herself.', duration: '46 min', thumbnail: 'https://picsum.photos/seed/bb1e3/320/180', rating: 8.6, airDate: '2024-05-31' },
          { id: 's30e4', number: 4, title: 'Street Food', description: 'A midnight food tour through Bangkok\'s best stalls brings the pair closer together.', duration: '47 min', thumbnail: 'https://picsum.photos/seed/bb1e4/320/180', rating: 8.7, airDate: '2024-06-07' },
          { id: 's30e5', number: 5, title: 'Full Bloom', description: 'As Michael\'s departure looms, Kanya must decide whether to finally take a chance on love.', duration: '48 min', thumbnail: 'https://picsum.photos/seed/bb1e5/320/180', rating: 8.8, airDate: '2024-06-14' },
        ],
      },
    ],
    cast: [
      { name: 'Urassaya Sperbund', role: 'Kanya', photo: 'https://picsum.photos/seed/cast114/100/100' },
      { name: 'Chantavit Dhanasevi', role: 'Michael Chen', photo: 'https://picsum.photos/seed/cast115/100/100' },
      { name: 'Davika Hoorne', role: 'Sister Ploy', photo: 'https://picsum.photos/seed/cast116/100/100' },
      { name: 'Nadech Kugimiya', role: 'Chef Wattana', photo: 'https://picsum.photos/seed/cast117/100/100' },
    ],
    status: 'Completed',
    studio: 'GMMTV',
    country: 'Thailand',
    language: 'Thai',
    totalEpisodes: 5,
    featured: false,
    trending: false,
  },
];

// Indexes
export const seriesMap = new Map(series.map((s) => [s.id, s]));

export function getSeriesById(id: string): Series | undefined {
  return seriesMap.get(id);
}

export function getFeaturedSeries(): Series[] {
  return series.filter((s) => s.featured);
}

export function getTrendingSeries(): Series[] {
  return series.filter((s) => s.trending);
}

export function getSeriesByGenre(genre: string): Series[] {
  return series.filter((s) => s.genre.includes(genre));
}

export function searchSeries(query: string): Series[] {
  const q = query.toLowerCase();
  return series.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.genre.some((g) => g.toLowerCase().includes(q)) ||
      s.cast.some((c) => c.name.toLowerCase().includes(q))
  );
}

export function getTopSeries(limit = 10): Series[] {
  return [...series].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getNewEpisodes(): Series[] {
  return series.filter((s) => s.status === 'Airing').slice(0, 10);
}

export function getRecentlyAdded(): Series[] {
  return [...series].sort((a, b) => b.year - a.year).slice(0, 10);
}

// Default continue watching data
export const defaultContinueWatching: WatchProgress[] = [
  { seriesId: 's1', seasonNumber: 1, episodeNumber: 3, progress: 65 },
  { seriesId: 's2', seasonNumber: 1, episodeNumber: 2, progress: 40 },
  { seriesId: 's4', seasonNumber: 2, episodeNumber: 1, progress: 80 },
  { seriesId: 's9', seasonNumber: 2, episodeNumber: 2, progress: 25 },
];
